title: Mark Roosjen
logo: /assets/img/head-2.jpg
description: I am a motivated and enthusiastic researcher whose professional ambition is to aid other clients in specific questions/needs with my expertise in proteomics and data analytics. My dedication is to produce results of excellent quality and reproducibility. With my ambitious personality I am always looking to figure out and implement new methodology to tackle specific problems. 
#show_downloads: true
theme: jekyll-theme-minimal
